/* BE CAREFUL ON HOW YOU PLAY THE SCENARIO
QUERIES MUST BE SELECTED AND THEN EXECUTED ONE BY ONE*/

/*Query 1*/
-- SNAPSHOT ISOLATION CAN ONLY BE USED IF DATABASE ALLOWS IT
-- SEE PAGE 14 OF THE BLACKBOARD FILE
SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
BEGIN TRANSACTION;

SELECT *
FROM iris_data;

DELETE FROM iris_data
WHERE [sepal length (cm)] >= 5;

-- CHOOSE CAREFULLY ONE OR ANOTHER
COMMIT;
ROLLBACK;

/*Query 2*/

SELECT *
FROM iris_data;

SELECT *
FROM iris_data
WHERE [sepal length (cm)] >= 5

UPDATE iris_data
SET [sepal length (cm)] = [sepal length (cm)] + 10
WHERE [sepal length (cm)] >= 5

ROLLBACK

